display_language: "zh-CN"

# API配置 - 使用环境变量
api:
  key: ${API_KEY}
  base_url: ${BASE_URL}
  model: ${MODEL}
  llm_support_json: false

# 语言设置
target_language: '简体中文'

# Railway优化配置
max_workers: 4  # Railway性能更好，可以增加并发
port: ${PORT}   # Railway动态端口

# Whisper设置
whisper:
  model: 'base'
  language: 'en'
  runtime: 'local'

# TTS设置
tts_method: 'edge_tts'

# 性能优化
demucs: false
ffmpeg_gpu: false
burn_subtitles: true
ytb_resolution: '1080'

# Edge TTS配置
edge_tts:
  voice: 'zh-CN-XiaoxiaoNeural'

# 音频速度设置
speed_factor:
  min: 1
  accept: 1.2
  max: 1.4
