# LLM配置 - 使用302.ai的Claude
llm:
  api_key: "sk-QzOKB3kU82rZcuh6Sy13oGm8pqjEFLQg5pQ3WlBwFUoDv08E"  # 替换为您的API密钥
  base_url: "https://api.302.ai"      # 302.ai的API地址
  model: "claude-3-5-sonnet-20241022" # Claude模型名称
  
# 语言设置
target_language: "简体中文"

# 其他推荐设置
whisper:
  model: "large-v3"
  device: "cpu"
  
tts:
  method: "edge_tts"  # 使用免费的Edge TTS
  
# 性能优化
max_workers: 4
chunk_size: 1000
